export const FETCH_COLLECTION_LOADING = 'FETCH_COLLECTION_LOADING';
export const FETCH_COLLECTION_SUCCEED = "FETCH_COLLECTION_SUCCEED";
export const FETCH_COLLECTION_FAILED = "FETCH_COLLECTION_FAILED";
