export const FAVORITES = "Favorites"
export const FAVORITES_INTRO = "A selection of mixes I enjoyed lately. A blend of house, electro and techno."
export const FAVORITE_1_NAME = "Silverlining"
export const FAVORITE_1_DESC = "I - Silverlining has been active since the 90s, he is one of the finest selector out there. This mix is largely electronic, oscillating between various styles from unknown mid 90s records to more recent ones, it twists and turns between moods and genres but keeps a groove throughout."
export const FAVORITE_1_LINK = "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/529977864&color=%23e5a655&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"
export const FAVORITE_2_NAME = "Van Anh"
export const FAVORITE_2_DESC = "II - Van Anh is a prominent figure of the Dutch techno scene. This mix carries a lot of dub grooves and atmospheric vibes which creates a thrilling techno journey. Be prepared to load for a mind trip."
export const FAVORITE_2_LINK = "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/499227549&color=%23e5a655&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"